/*
 * Copyright (c) 2003, 2007-14 Matteo Frigo
 * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

/* This file was automatically generated --- DO NOT EDIT */
/* Generated on Tue Sep 14 10:45:58 EDT 2021 */

#include "dft/codelet-dft.h"

#if defined(ARCH_PREFERS_FMA) || defined(ISA_EXTENSION_PREFERS_FMA)

/* Generated by: ../../../genfft/gen_twiddle.native -fma -simd -compact -variables 4 -pipeline-latency 8 -n 32 -name t1sv_32 -include dft/simd/ts.h */

/*
 * This function contains 434 FP additions, 260 FP multiplications,
 * (or, 236 additions, 62 multiplications, 198 fused multiply/add),
 * 102 stack variables, 7 constants, and 128 memory accesses
 */
#include "dft/simd/ts.h"

static void t1sv_32(R *ri, R *ii, const R *W, stride rs, INT mb, INT me, INT ms)
{
     DVK(KP980785280, +0.980785280403230449126182236134239036973933731);
     DVK(KP831469612, +0.831469612302545237078788377617905756738560812);
     DVK(KP198912367, +0.198912367379658006911597622644676228597850501);
     DVK(KP668178637, +0.668178637919298919997757686523080761552472251);
     DVK(KP923879532, +0.923879532511286756128183189396788286822416626);
     DVK(KP414213562, +0.414213562373095048801688724209698078569671875);
     DVK(KP707106781, +0.707106781186547524400844362104849039284835938);
     {
	  INT m;
	  for (m = mb, W = W + (mb * 62); m < me; m = m + (2 * VL), ri = ri + ((2 * VL) * ms), ii = ii + ((2 * VL) * ms), W = W + ((2 * VL) * 62), MAKE_VOLATILE_STRIDE(64, rs)) {
	       V T8, T8x, T3w, T87, Tl, T8y, T3B, T83, Tz, T6F, T3J, T5T, TM, T6G, T3Q;
	       V T5U, T11, T1e, T6M, T6J, T6K, T6L, T3Z, T5X, T46, T5Y, T1s, T1F, T6O, T6P;
	       V T6Q, T6R, T4e, T60, T4l, T61, T32, T7b, T78, T7N, T54, T6f, T5r, T6c, T29;
	       V T70, T6X, T7I, T4v, T68, T4S, T65, T3t, T79, T7e, T7O, T5b, T5s, T5i, T5t;
	       V T2A, T6Y, T73, T7J, T4C, T4T, T4J, T4U;
	       {
		    V T1, T86, T3, T6, T4, T84, T2, T7, T85, T5;
		    T1 = LD(&(ri[0]), ms, &(ri[0]));
		    T86 = LD(&(ii[0]), ms, &(ii[0]));
		    T3 = LD(&(ri[WS(rs, 16)]), ms, &(ri[0]));
		    T6 = LD(&(ii[WS(rs, 16)]), ms, &(ii[0]));
		    T2 = LDW(&(W[TWVL * 30]));
		    T4 = VMUL(T2, T3);
		    T84 = VMUL(T2, T6);
		    T5 = LDW(&(W[TWVL * 31]));
		    T7 = VFMA(T5, T6, T4);
		    T85 = VFNMS(T5, T3, T84);
		    T8 = VADD(T1, T7);
		    T8x = VSUB(T86, T85);
		    T3w = VSUB(T1, T7);
		    T87 = VADD(T85, T86);
	       }
	       {
		    V Ta, Td, Tb, T3x, Tg, Tj, Th, T3z, T9, Tf;
		    Ta = LD(&(ri[WS(rs, 8)]), ms, &(ri[0]));
		    Td = LD(&(ii[WS(rs, 8)]), ms, &(ii[0]));
		    T9 = LDW(&(W[TWVL * 14]));
		    Tb = VMUL(T9, Ta);
		    T3x = VMUL(T9, Td);
		    Tg = LD(&(ri[WS(rs, 24)]), ms, &(ri[0]));
		    Tj = LD(&(ii[WS(rs, 24)]), ms, &(ii[0]));
		    Tf = LDW(&(W[TWVL * 46]));
		    Th = VMUL(Tf, Tg);
		    T3z = VMUL(Tf, Tj);
		    {
			 V Te, T3y, Tk, T3A, Tc, Ti;
			 Tc = LDW(&(W[TWVL * 15]));
			 Te = VFMA(Tc, Td, Tb);
			 T3y = VFNMS(Tc, Ta, T3x);
			 Ti = LDW(&(W[TWVL * 47]));
			 Tk = VFMA(Ti, Tj, Th);
			 T3A = VFNMS(Ti, Tg, T3z);
			 Tl = VADD(Te, Tk);
			 T8y = VSUB(Te, Tk);
			 T3B = VSUB(T3y, T3A);
			 T83 = VADD(T3y, T3A);
		    }
	       }
	       {
		    V Ts, T3F, Ty, T3H, T3D, T3I;
		    {
			 V To, Tr, Tp, T3E, Tn, Tq;
			 To = LD(&(ri[WS(rs, 4)]), ms, &(ri[0]));
			 Tr = LD(&(ii[WS(rs, 4)]), ms, &(ii[0]));
			 Tn = LDW(&(W[TWVL * 6]));
			 Tp = VMUL(Tn, To);
			 T3E = VMUL(Tn, Tr);
			 Tq = LDW(&(W[TWVL * 7]));
			 Ts = VFMA(Tq, Tr, Tp);
			 T3F = VFNMS(Tq, To, T3E);
		    }
		    {
			 V Tu, Tx, Tv, T3G, Tt, Tw;
			 Tu = LD(&(ri[WS(rs, 20)]), ms, &(ri[0]));
			 Tx = LD(&(ii[WS(rs, 20)]), ms, &(ii[0]));
			 Tt = LDW(&(W[TWVL * 38]));
			 Tv = VMUL(Tt, Tu);
			 T3G = VMUL(Tt, Tx);
			 Tw = LDW(&(W[TWVL * 39]));
			 Ty = VFMA(Tw, Tx, Tv);
			 T3H = VFNMS(Tw, Tu, T3G);
		    }
		    Tz = VADD(Ts, Ty);
		    T6F = VADD(T3F, T3H);
		    T3D = VSUB(Ts, Ty);
		    T3I = VSUB(T3F, T3H);
		    T3J = VADD(T3D, T3I);
		    T5T = VSUB(T3I, T3D);
	       }
	       {
		    V TF, T3M, TL, T3O, T3K, T3P;
		    {
			 V TB, TE, TC, T3L, TA, TD;
			 TB = LD(&(ri[WS(rs, 28)]), ms, &(ri[0]));
			 TE = LD(&(ii[WS(rs, 28)]), ms, &(ii[0]));
			 TA = LDW(&(W[TWVL * 54]));
			 TC = VMUL(TA, TB);
			 T3L = VMUL(TA, TE);
			 TD = LDW(&(W[TWVL * 55]));
			 TF = VFMA(TD, TE, TC);
			 T3M = VFNMS(TD, TB, T3L);
		    }
		    {
			 V TH, TK, TI, T3N, TG, TJ;
			 TH = LD(&(ri[WS(rs, 12)]), ms, &(ri[0]));
			 TK = LD(&(ii[WS(rs, 12)]), ms, &(ii[0]));
			 TG = LDW(&(W[TWVL * 22]));
			 TI = VMUL(TG, TH);
			 T3N = VMUL(TG, TK);
			 TJ = LDW(&(W[TWVL * 23]));
			 TL = VFMA(TJ, TK, TI);
			 T3O = VFNMS(TJ, TH, T3N);
		    }
		    TM = VADD(TF, TL);
		    T6G = VADD(T3M, T3O);
		    T3K = VSUB(TF, TL);
		    T3P = VSUB(T3M, T3O);
		    T3Q = VSUB(T3K, T3P);
		    T5U = VADD(T3K, T3P);
	       }
	       {
		    V TU, T3U, T1d, T44, T10, T3W, T17, T42;
		    {
			 V TQ, TT, TR, T3T, TP, TS;
			 TQ = LD(&(ri[WS(rs, 2)]), ms, &(ri[0]));
			 TT = LD(&(ii[WS(rs, 2)]), ms, &(ii[0]));
			 TP = LDW(&(W[TWVL * 2]));
			 TR = VMUL(TP, TQ);
			 T3T = VMUL(TP, TT);
			 TS = LDW(&(W[TWVL * 3]));
			 TU = VFMA(TS, TT, TR);
			 T3U = VFNMS(TS, TQ, T3T);
		    }
		    {
			 V T19, T1c, T1a, T43, T18, T1b;
			 T19 = LD(&(ri[WS(rs, 26)]), ms, &(ri[0]));
			 T1c = LD(&(ii[WS(rs, 26)]), ms, &(ii[0]));
			 T18 = LDW(&(W[TWVL * 50]));
			 T1a = VMUL(T18, T19);
			 T43 = VMUL(T18, T1c);
			 T1b = LDW(&(W[TWVL * 51]));
			 T1d = VFMA(T1b, T1c, T1a);
			 T44 = VFNMS(T1b, T19, T43);
		    }
		    {
			 V TW, TZ, TX, T3V, TV, TY;
			 TW = LD(&(ri[WS(rs, 18)]), ms, &(ri[0]));
			 TZ = LD(&(ii[WS(rs, 18)]), ms, &(ii[0]));
			 TV = LDW(&(W[TWVL * 34]));
			 TX = VMUL(TV, TW);
			 T3V = VMUL(TV, TZ);
			 TY = LDW(&(W[TWVL * 35]));
			 T10 = VFMA(TY, TZ, TX);
			 T3W = VFNMS(TY, TW, T3V);
		    }
		    {
			 V T13, T16, T14, T41, T12, T15;
			 T13 = LD(&(ri[WS(rs, 10)]), ms, &(ri[0]));
			 T16 = LD(&(ii[WS(rs, 10)]), ms, &(ii[0]));
			 T12 = LDW(&(W[TWVL * 18]));
			 T14 = VMUL(T12, T13);
			 T41 = VMUL(T12, T16);
			 T15 = LDW(&(W[TWVL * 19]));
			 T17 = VFMA(T15, T16, T14);
			 T42 = VFNMS(T15, T13, T41);
		    }
		    T11 = VADD(TU, T10);
		    T1e = VADD(T17, T1d);
		    T6M = VSUB(T11, T1e);
		    T6J = VADD(T3U, T3W);
		    T6K = VADD(T42, T44);
		    T6L = VSUB(T6J, T6K);
		    {
			 V T3X, T3Y, T40, T45;
			 T3X = VSUB(T3U, T3W);
			 T3Y = VSUB(T17, T1d);
			 T3Z = VSUB(T3X, T3Y);
			 T5X = VADD(T3X, T3Y);
			 T40 = VSUB(TU, T10);
			 T45 = VSUB(T42, T44);
			 T46 = VADD(T40, T45);
			 T5Y = VSUB(T40, T45);
		    }
	       }
	       {
		    V T1l, T49, T1E, T4j, T1r, T4b, T1y, T4h;
		    {
			 V T1h, T1k, T1i, T48, T1g, T1j;
			 T1h = LD(&(ri[WS(rs, 30)]), ms, &(ri[0]));
			 T1k = LD(&(ii[WS(rs, 30)]), ms, &(ii[0]));
			 T1g = LDW(&(W[TWVL * 58]));
			 T1i = VMUL(T1g, T1h);
			 T48 = VMUL(T1g, T1k);
			 T1j = LDW(&(W[TWVL * 59]));
			 T1l = VFMA(T1j, T1k, T1i);
			 T49 = VFNMS(T1j, T1h, T48);
		    }
		    {
			 V T1A, T1D, T1B, T4i, T1z, T1C;
			 T1A = LD(&(ri[WS(rs, 22)]), ms, &(ri[0]));
			 T1D = LD(&(ii[WS(rs, 22)]), ms, &(ii[0]));
			 T1z = LDW(&(W[TWVL * 42]));
			 T1B = VMUL(T1z, T1A);
			 T4i = VMUL(T1z, T1D);
			 T1C = LDW(&(W[TWVL * 43]));
			 T1E = VFMA(T1C, T1D, T1B);
			 T4j = VFNMS(T1C, T1A, T4i);
		    }
		    {
			 V T1n, T1q, T1o, T4a, T1m, T1p;
			 T1n = LD(&(ri[WS(rs, 14)]), ms, &(ri[0]));
			 T1q = LD(&(ii[WS(rs, 14)]), ms, &(ii[0]));
			 T1m = LDW(&(W[TWVL * 26]));
			 T1o = VMUL(T1m, T1n);
			 T4a = VMUL(T1m, T1q);
			 T1p = LDW(&(W[TWVL * 27]));
			 T1r = VFMA(T1p, T1q, T1o);
			 T4b = VFNMS(T1p, T1n, T4a);
		    }
		    {
			 V T1u, T1x, T1v, T4g, T1t, T1w;
			 T1u = LD(&(ri[WS(rs, 6)]), ms, &(ri[0]));
			 T1x = LD(&(ii[WS(rs, 6)]), ms, &(ii[0]));
			 T1t = LDW(&(W[TWVL * 10]));
			 T1v = VMUL(T1t, T1u);
			 T4g = VMUL(T1t, T1x);
			 T1w = LDW(&(W[TWVL * 11]));
			 T1y = VFMA(T1w, T1x, T1v);
			 T4h = VFNMS(T1w, T1u, T4g);
		    }
		    T1s = VADD(T1l, T1r);
		    T1F = VADD(T1y, T1E);
		    T6O = VSUB(T1s, T1F);
		    T6P = VADD(T49, T4b);
		    T6Q = VADD(T4h, T4j);
		    T6R = VSUB(T6P, T6Q);
		    {
			 V T4c, T4d, T4f, T4k;
			 T4c = VSUB(T49, T4b);
			 T4d = VSUB(T1y, T1E);
			 T4e = VSUB(T4c, T4d);
			 T60 = VADD(T4c, T4d);
			 T4f = VSUB(T1l, T1r);
			 T4k = VSUB(T4h, T4j);
			 T4l = VADD(T4f, T4k);
			 T61 = VSUB(T4f, T4k);
		    }
	       }
	       {
		    V T2H, T4Z, T30, T5p, T2N, T51, T2U, T5n;
		    {
			 V T2D, T2G, T2E, T4Y, T2C, T2F;
			 T2D = LD(&(ri[WS(rs, 31)]), ms, &(ri[WS(rs, 1)]));
			 T2G = LD(&(ii[WS(rs, 31)]), ms, &(ii[WS(rs, 1)]));
			 T2C = LDW(&(W[TWVL * 60]));
			 T2E = VMUL(T2C, T2D);
			 T4Y = VMUL(T2C, T2G);
			 T2F = LDW(&(W[TWVL * 61]));
			 T2H = VFMA(T2F, T2G, T2E);
			 T4Z = VFNMS(T2F, T2D, T4Y);
		    }
		    {
			 V T2W, T2Z, T2X, T5o, T2V, T2Y;
			 T2W = LD(&(ri[WS(rs, 23)]), ms, &(ri[WS(rs, 1)]));
			 T2Z = LD(&(ii[WS(rs, 23)]), ms, &(ii[WS(rs, 1)]));
			 T2V = LDW(&(W[TWVL * 44]));
			 T2X = VMUL(T2V, T2W);
			 T5o = VMUL(T2V, T2Z);
			 T2Y = LDW(&(W[TWVL * 45]));
			 T30 = VFMA(T2Y, T2Z, T2X);
			 T5p = VFNMS(T2Y, T2W, T5o);
		    }
		    {
			 V T2J, T2M, T2K, T50, T2I, T2L;
			 T2J = LD(&(ri[WS(rs, 15)]), ms, &(ri[WS(rs, 1)]));
			 T2M = LD(&(ii[WS(rs, 15)]), ms, &(ii[WS(rs, 1)]));
			 T2I = LDW(&(W[TWVL * 28]));
			 T2K = VMUL(T2I, T2J);
			 T50 = VMUL(T2I, T2M);
			 T2L = LDW(&(W[TWVL * 29]));
			 T2N = VFMA(T2L, T2M, T2K);
			 T51 = VFNMS(T2L, T2J, T50);
		    }
		    {
			 V T2Q, T2T, T2R, T5m, T2P, T2S;
			 T2Q = LD(&(ri[WS(rs, 7)]), ms, &(ri[WS(rs, 1)]));
			 T2T = LD(&(ii[WS(rs, 7)]), ms, &(ii[WS(rs, 1)]));
			 T2P = LDW(&(W[TWVL * 12]));
			 T2R = VMUL(T2P, T2Q);
			 T5m = VMUL(T2P, T2T);
			 T2S = LDW(&(W[TWVL * 13]));
			 T2U = VFMA(T2S, T2T, T2R);
			 T5n = VFNMS(T2S, T2Q, T5m);
		    }
		    {
			 V T2O, T31, T76, T77;
			 T2O = VADD(T2H, T2N);
			 T31 = VADD(T2U, T30);
			 T32 = VADD(T2O, T31);
			 T7b = VSUB(T2O, T31);
			 T76 = VADD(T4Z, T51);
			 T77 = VADD(T5n, T5p);
			 T78 = VSUB(T76, T77);
			 T7N = VADD(T76, T77);
		    }
		    {
			 V T52, T53, T5l, T5q;
			 T52 = VSUB(T4Z, T51);
			 T53 = VSUB(T2U, T30);
			 T54 = VSUB(T52, T53);
			 T6f = VADD(T52, T53);
			 T5l = VSUB(T2H, T2N);
			 T5q = VSUB(T5n, T5p);
			 T5r = VADD(T5l, T5q);
			 T6c = VSUB(T5l, T5q);
		    }
	       }
	       {
		    V T1O, T4q, T27, T4Q, T1U, T4s, T21, T4O;
		    {
			 V T1K, T1N, T1L, T4p, T1J, T1M;
			 T1K = LD(&(ri[WS(rs, 1)]), ms, &(ri[WS(rs, 1)]));
			 T1N = LD(&(ii[WS(rs, 1)]), ms, &(ii[WS(rs, 1)]));
			 T1J = LDW(&(W[0]));
			 T1L = VMUL(T1J, T1K);
			 T4p = VMUL(T1J, T1N);
			 T1M = LDW(&(W[TWVL * 1]));
			 T1O = VFMA(T1M, T1N, T1L);
			 T4q = VFNMS(T1M, T1K, T4p);
		    }
		    {
			 V T23, T26, T24, T4P, T22, T25;
			 T23 = LD(&(ri[WS(rs, 25)]), ms, &(ri[WS(rs, 1)]));
			 T26 = LD(&(ii[WS(rs, 25)]), ms, &(ii[WS(rs, 1)]));
			 T22 = LDW(&(W[TWVL * 48]));
			 T24 = VMUL(T22, T23);
			 T4P = VMUL(T22, T26);
			 T25 = LDW(&(W[TWVL * 49]));
			 T27 = VFMA(T25, T26, T24);
			 T4Q = VFNMS(T25, T23, T4P);
		    }
		    {
			 V T1Q, T1T, T1R, T4r, T1P, T1S;
			 T1Q = LD(&(ri[WS(rs, 17)]), ms, &(ri[WS(rs, 1)]));
			 T1T = LD(&(ii[WS(rs, 17)]), ms, &(ii[WS(rs, 1)]));
			 T1P = LDW(&(W[TWVL * 32]));
			 T1R = VMUL(T1P, T1Q);
			 T4r = VMUL(T1P, T1T);
			 T1S = LDW(&(W[TWVL * 33]));
			 T1U = VFMA(T1S, T1T, T1R);
			 T4s = VFNMS(T1S, T1Q, T4r);
		    }
		    {
			 V T1X, T20, T1Y, T4N, T1W, T1Z;
			 T1X = LD(&(ri[WS(rs, 9)]), ms, &(ri[WS(rs, 1)]));
			 T20 = LD(&(ii[WS(rs, 9)]), ms, &(ii[WS(rs, 1)]));
			 T1W = LDW(&(W[TWVL * 16]));
			 T1Y = VMUL(T1W, T1X);
			 T4N = VMUL(T1W, T20);
			 T1Z = LDW(&(W[TWVL * 17]));
			 T21 = VFMA(T1Z, T20, T1Y);
			 T4O = VFNMS(T1Z, T1X, T4N);
		    }
		    {
			 V T1V, T28, T6V, T6W;
			 T1V = VADD(T1O, T1U);
			 T28 = VADD(T21, T27);
			 T29 = VADD(T1V, T28);
			 T70 = VSUB(T1V, T28);
			 T6V = VADD(T4q, T4s);
			 T6W = VADD(T4O, T4Q);
			 T6X = VSUB(T6V, T6W);
			 T7I = VADD(T6V, T6W);
		    }
		    {
			 V T4t, T4u, T4M, T4R;
			 T4t = VSUB(T4q, T4s);
			 T4u = VSUB(T21, T27);
			 T4v = VSUB(T4t, T4u);
			 T68 = VADD(T4t, T4u);
			 T4M = VSUB(T1O, T1U);
			 T4R = VSUB(T4O, T4Q);
			 T4S = VADD(T4M, T4R);
			 T65 = VSUB(T4M, T4R);
		    }
	       }
	       {
		    V T38, T56, T3r, T5g, T3e, T58, T3l, T5e;
		    {
			 V T34, T37, T35, T55, T33, T36;
			 T34 = LD(&(ri[WS(rs, 3)]), ms, &(ri[WS(rs, 1)]));
			 T37 = LD(&(ii[WS(rs, 3)]), ms, &(ii[WS(rs, 1)]));
			 T33 = LDW(&(W[TWVL * 4]));
			 T35 = VMUL(T33, T34);
			 T55 = VMUL(T33, T37);
			 T36 = LDW(&(W[TWVL * 5]));
			 T38 = VFMA(T36, T37, T35);
			 T56 = VFNMS(T36, T34, T55);
		    }
		    {
			 V T3n, T3q, T3o, T5f, T3m, T3p;
			 T3n = LD(&(ri[WS(rs, 11)]), ms, &(ri[WS(rs, 1)]));
			 T3q = LD(&(ii[WS(rs, 11)]), ms, &(ii[WS(rs, 1)]));
			 T3m = LDW(&(W[TWVL * 20]));
			 T3o = VMUL(T3m, T3n);
			 T5f = VMUL(T3m, T3q);
			 T3p = LDW(&(W[TWVL * 21]));
			 T3r = VFMA(T3p, T3q, T3o);
			 T5g = VFNMS(T3p, T3n, T5f);
		    }
		    {
			 V T3a, T3d, T3b, T57, T39, T3c;
			 T3a = LD(&(ri[WS(rs, 19)]), ms, &(ri[WS(rs, 1)]));
			 T3d = LD(&(ii[WS(rs, 19)]), ms, &(ii[WS(rs, 1)]));
			 T39 = LDW(&(W[TWVL * 36]));
			 T3b = VMUL(T39, T3a);
			 T57 = VMUL(T39, T3d);
			 T3c = LDW(&(W[TWVL * 37]));
			 T3e = VFMA(T3c, T3d, T3b);
			 T58 = VFNMS(T3c, T3a, T57);
		    }
		    {
			 V T3h, T3k, T3i, T5d, T3g, T3j;
			 T3h = LD(&(ri[WS(rs, 27)]), ms, &(ri[WS(rs, 1)]));
			 T3k = LD(&(ii[WS(rs, 27)]), ms, &(ii[WS(rs, 1)]));
			 T3g = LDW(&(W[TWVL * 52]));
			 T3i = VMUL(T3g, T3h);
			 T5d = VMUL(T3g, T3k);
			 T3j = LDW(&(W[TWVL * 53]));
			 T3l = VFMA(T3j, T3k, T3i);
			 T5e = VFNMS(T3j, T3h, T5d);
		    }
		    {
			 V T3f, T3s, T7c, T7d;
			 T3f = VADD(T38, T3e);
			 T3s = VADD(T3l, T3r);
			 T3t = VADD(T3f, T3s);
			 T79 = VSUB(T3s, T3f);
			 T7c = VADD(T56, T58);
			 T7d = VADD(T5e, T5g);
			 T7e = VSUB(T7c, T7d);
			 T7O = VADD(T7c, T7d);
		    }
		    {
			 V T59, T5a, T5c, T5h;
			 T59 = VSUB(T56, T58);
			 T5a = VSUB(T38, T3e);
			 T5b = VSUB(T59, T5a);
			 T5s = VADD(T5a, T59);
			 T5c = VSUB(T3l, T3r);
			 T5h = VSUB(T5e, T5g);
			 T5i = VADD(T5c, T5h);
			 T5t = VSUB(T5c, T5h);
		    }
	       }
	       {
		    V T2f, T4x, T2y, T4H, T2l, T4z, T2s, T4F;
		    {
			 V T2b, T2e, T2c, T4w, T2a, T2d;
			 T2b = LD(&(ri[WS(rs, 5)]), ms, &(ri[WS(rs, 1)]));
			 T2e = LD(&(ii[WS(rs, 5)]), ms, &(ii[WS(rs, 1)]));
			 T2a = LDW(&(W[TWVL * 8]));
			 T2c = VMUL(T2a, T2b);
			 T4w = VMUL(T2a, T2e);
			 T2d = LDW(&(W[TWVL * 9]));
			 T2f = VFMA(T2d, T2e, T2c);
			 T4x = VFNMS(T2d, T2b, T4w);
		    }
		    {
			 V T2u, T2x, T2v, T4G, T2t, T2w;
			 T2u = LD(&(ri[WS(rs, 13)]), ms, &(ri[WS(rs, 1)]));
			 T2x = LD(&(ii[WS(rs, 13)]), ms, &(ii[WS(rs, 1)]));
			 T2t = LDW(&(W[TWVL * 24]));
			 T2v = VMUL(T2t, T2u);
			 T4G = VMUL(T2t, T2x);
			 T2w = LDW(&(W[TWVL * 25]));
			 T2y = VFMA(T2w, T2x, T2v);
			 T4H = VFNMS(T2w, T2u, T4G);
		    }
		    {
			 V T2h, T2k, T2i, T4y, T2g, T2j;
			 T2h = LD(&(ri[WS(rs, 21)]), ms, &(ri[WS(rs, 1)]));
			 T2k = LD(&(ii[WS(rs, 21)]), ms, &(ii[WS(rs, 1)]));
			 T2g = LDW(&(W[TWVL * 40]));
			 T2i = VMUL(T2g, T2h);
			 T4y = VMUL(T2g, T2k);
			 T2j = LDW(&(W[TWVL * 41]));
			 T2l = VFMA(T2j, T2k, T2i);
			 T4z = VFNMS(T2j, T2h, T4y);
		    }
		    {
			 V T2o, T2r, T2p, T4E, T2n, T2q;
			 T2o = LD(&(ri[WS(rs, 29)]), ms, &(ri[WS(rs, 1)]));
			 T2r = LD(&(ii[WS(rs, 29)]), ms, &(ii[WS(rs, 1)]));
			 T2n = LDW(&(W[TWVL * 56]));
			 T2p = VMUL(T2n, T2o);
			 T4E = VMUL(T2n, T2r);
			 T2q = LDW(&(W[TWVL * 57]));
			 T2s = VFMA(T2q, T2r, T2p);
			 T4F = VFNMS(T2q, T2o, T4E);
		    }
		    {
			 V T2m, T2z, T71, T72;
			 T2m = VADD(T2f, T2l);
			 T2z = VADD(T2s, T2y);
			 T2A = VADD(T2m, T2z);
			 T6Y = VSUB(T2z, T2m);
			 T71 = VADD(T4x, T4z);
			 T72 = VADD(T4F, T4H);
			 T73 = VSUB(T71, T72);
			 T7J = VADD(T71, T72);
		    }
		    {
			 V T4A, T4B, T4D, T4I;
			 T4A = VSUB(T4x, T4z);
			 T4B = VSUB(T2f, T2l);
			 T4C = VSUB(T4A, T4B);
			 T4T = VADD(T4B, T4A);
			 T4D = VSUB(T2s, T2y);
			 T4I = VSUB(T4F, T4H);
			 T4J = VADD(T4D, T4I);
			 T4U = VSUB(T4D, T4I);
		    }
	       }
	       {
		    V TO, T7C, T7Z, T80, T89, T8e, T1H, T8d, T3v, T8b, T7L, T7T, T7Q, T7U, T7F;
		    V T81;
		    {
			 V Tm, TN, T7X, T7Y;
			 Tm = VADD(T8, Tl);
			 TN = VADD(Tz, TM);
			 TO = VADD(Tm, TN);
			 T7C = VSUB(Tm, TN);
			 T7X = VADD(T7I, T7J);
			 T7Y = VADD(T7N, T7O);
			 T7Z = VSUB(T7X, T7Y);
			 T80 = VADD(T7X, T7Y);
		    }
		    {
			 V T82, T88, T1f, T1G;
			 T82 = VADD(T6F, T6G);
			 T88 = VADD(T83, T87);
			 T89 = VADD(T82, T88);
			 T8e = VSUB(T88, T82);
			 T1f = VADD(T11, T1e);
			 T1G = VADD(T1s, T1F);
			 T1H = VADD(T1f, T1G);
			 T8d = VSUB(T1G, T1f);
		    }
		    {
			 V T2B, T3u, T7H, T7K;
			 T2B = VADD(T29, T2A);
			 T3u = VADD(T32, T3t);
			 T3v = VADD(T2B, T3u);
			 T8b = VSUB(T3u, T2B);
			 T7H = VSUB(T29, T2A);
			 T7K = VSUB(T7I, T7J);
			 T7L = VADD(T7H, T7K);
			 T7T = VSUB(T7K, T7H);
		    }
		    {
			 V T7M, T7P, T7D, T7E;
			 T7M = VSUB(T32, T3t);
			 T7P = VSUB(T7N, T7O);
			 T7Q = VSUB(T7M, T7P);
			 T7U = VADD(T7M, T7P);
			 T7D = VADD(T6J, T6K);
			 T7E = VADD(T6P, T6Q);
			 T7F = VSUB(T7D, T7E);
			 T81 = VADD(T7D, T7E);
		    }
		    {
			 V T1I, T8a, T7W, T8c;
			 T1I = VADD(TO, T1H);
			 ST(&(ri[WS(rs, 16)]), VSUB(T1I, T3v), ms, &(ri[0]));
			 ST(&(ri[0]), VADD(T1I, T3v), ms, &(ri[0]));
			 T8a = VADD(T81, T89);
			 ST(&(ii[0]), VADD(T80, T8a), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 16)]), VSUB(T8a, T80), ms, &(ii[0]));
			 T7W = VSUB(TO, T1H);
			 ST(&(ri[WS(rs, 24)]), VSUB(T7W, T7Z), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 8)]), VADD(T7W, T7Z), ms, &(ri[0]));
			 T8c = VSUB(T89, T81);
			 ST(&(ii[WS(rs, 8)]), VADD(T8b, T8c), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 24)]), VSUB(T8c, T8b), ms, &(ii[0]));
		    }
		    {
			 V T7G, T7R, T8f, T8g;
			 T7G = VADD(T7C, T7F);
			 T7R = VADD(T7L, T7Q);
			 ST(&(ri[WS(rs, 20)]), VFNMS(LDK(KP707106781), T7R, T7G), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 4)]), VFMA(LDK(KP707106781), T7R, T7G), ms, &(ri[0]));
			 T8f = VADD(T8d, T8e);
			 T8g = VADD(T7T, T7U);
			 ST(&(ii[WS(rs, 4)]), VFMA(LDK(KP707106781), T8g, T8f), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 20)]), VFNMS(LDK(KP707106781), T8g, T8f), ms, &(ii[0]));
		    }
		    {
			 V T7S, T7V, T8h, T8i;
			 T7S = VSUB(T7C, T7F);
			 T7V = VSUB(T7T, T7U);
			 ST(&(ri[WS(rs, 28)]), VFNMS(LDK(KP707106781), T7V, T7S), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 12)]), VFMA(LDK(KP707106781), T7V, T7S), ms, &(ri[0]));
			 T8h = VSUB(T8e, T8d);
			 T8i = VSUB(T7Q, T7L);
			 ST(&(ii[WS(rs, 12)]), VFMA(LDK(KP707106781), T8i, T8h), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 28)]), VFNMS(LDK(KP707106781), T8i, T8h), ms, &(ii[0]));
		    }
	       }
	       {
		    V T6I, T7m, T7w, T7A, T8l, T8r, T6T, T8m, T75, T7j, T7p, T8s, T7t, T7z, T7g;
		    V T7k;
		    {
			 V T6E, T6H, T7u, T7v;
			 T6E = VSUB(T8, Tl);
			 T6H = VSUB(T6F, T6G);
			 T6I = VSUB(T6E, T6H);
			 T7m = VADD(T6E, T6H);
			 T7u = VADD(T7b, T7e);
			 T7v = VADD(T78, T79);
			 T7w = VFNMS(LDK(KP414213562), T7v, T7u);
			 T7A = VFMA(LDK(KP414213562), T7u, T7v);
		    }
		    {
			 V T8j, T8k, T6N, T6S;
			 T8j = VSUB(TM, Tz);
			 T8k = VSUB(T87, T83);
			 T8l = VADD(T8j, T8k);
			 T8r = VSUB(T8k, T8j);
			 T6N = VSUB(T6L, T6M);
			 T6S = VADD(T6O, T6R);
			 T6T = VSUB(T6N, T6S);
			 T8m = VADD(T6N, T6S);
		    }
		    {
			 V T6Z, T74, T7n, T7o;
			 T6Z = VSUB(T6X, T6Y);
			 T74 = VSUB(T70, T73);
			 T75 = VFMA(LDK(KP414213562), T74, T6Z);
			 T7j = VFNMS(LDK(KP414213562), T6Z, T74);
			 T7n = VADD(T6M, T6L);
			 T7o = VSUB(T6O, T6R);
			 T7p = VADD(T7n, T7o);
			 T8s = VSUB(T7o, T7n);
		    }
		    {
			 V T7r, T7s, T7a, T7f;
			 T7r = VADD(T70, T73);
			 T7s = VADD(T6X, T6Y);
			 T7t = VFMA(LDK(KP414213562), T7s, T7r);
			 T7z = VFNMS(LDK(KP414213562), T7r, T7s);
			 T7a = VSUB(T78, T79);
			 T7f = VSUB(T7b, T7e);
			 T7g = VFNMS(LDK(KP414213562), T7f, T7a);
			 T7k = VFMA(LDK(KP414213562), T7a, T7f);
		    }
		    {
			 V T6U, T7h, T8t, T8u;
			 T6U = VFMA(LDK(KP707106781), T6T, T6I);
			 T7h = VSUB(T75, T7g);
			 ST(&(ri[WS(rs, 22)]), VFNMS(LDK(KP923879532), T7h, T6U), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 6)]), VFMA(LDK(KP923879532), T7h, T6U), ms, &(ri[0]));
			 T8t = VFMA(LDK(KP707106781), T8s, T8r);
			 T8u = VSUB(T7k, T7j);
			 ST(&(ii[WS(rs, 6)]), VFMA(LDK(KP923879532), T8u, T8t), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 22)]), VFNMS(LDK(KP923879532), T8u, T8t), ms, &(ii[0]));
		    }
		    {
			 V T7i, T7l, T8v, T8w;
			 T7i = VFNMS(LDK(KP707106781), T6T, T6I);
			 T7l = VADD(T7j, T7k);
			 ST(&(ri[WS(rs, 14)]), VFNMS(LDK(KP923879532), T7l, T7i), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 30)]), VFMA(LDK(KP923879532), T7l, T7i), ms, &(ri[0]));
			 T8v = VFNMS(LDK(KP707106781), T8s, T8r);
			 T8w = VADD(T75, T7g);
			 ST(&(ii[WS(rs, 14)]), VFNMS(LDK(KP923879532), T8w, T8v), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 30)]), VFMA(LDK(KP923879532), T8w, T8v), ms, &(ii[0]));
		    }
		    {
			 V T7q, T7x, T8n, T8o;
			 T7q = VFMA(LDK(KP707106781), T7p, T7m);
			 T7x = VADD(T7t, T7w);
			 ST(&(ri[WS(rs, 18)]), VFNMS(LDK(KP923879532), T7x, T7q), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 2)]), VFMA(LDK(KP923879532), T7x, T7q), ms, &(ri[0]));
			 T8n = VFMA(LDK(KP707106781), T8m, T8l);
			 T8o = VADD(T7z, T7A);
			 ST(&(ii[WS(rs, 2)]), VFMA(LDK(KP923879532), T8o, T8n), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 18)]), VFNMS(LDK(KP923879532), T8o, T8n), ms, &(ii[0]));
		    }
		    {
			 V T7y, T7B, T8p, T8q;
			 T7y = VFNMS(LDK(KP707106781), T7p, T7m);
			 T7B = VSUB(T7z, T7A);
			 ST(&(ri[WS(rs, 26)]), VFNMS(LDK(KP923879532), T7B, T7y), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 10)]), VFMA(LDK(KP923879532), T7B, T7y), ms, &(ri[0]));
			 T8p = VFNMS(LDK(KP707106781), T8m, T8l);
			 T8q = VSUB(T7w, T7t);
			 ST(&(ii[WS(rs, 10)]), VFMA(LDK(KP923879532), T8q, T8p), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 26)]), VFNMS(LDK(KP923879532), T8q, T8p), ms, &(ii[0]));
		    }
	       }
	       {
		    V T3S, T5C, T4n, T8C, T8B, T8H, T5F, T8I, T5w, T5Q, T5A, T5M, T4X, T5P, T5z;
		    V T5J;
		    {
			 V T3C, T3R, T5D, T5E;
			 T3C = VADD(T3w, T3B);
			 T3R = VADD(T3J, T3Q);
			 T3S = VFNMS(LDK(KP707106781), T3R, T3C);
			 T5C = VFMA(LDK(KP707106781), T3R, T3C);
			 {
			      V T47, T4m, T8z, T8A;
			      T47 = VFNMS(LDK(KP414213562), T46, T3Z);
			      T4m = VFMA(LDK(KP414213562), T4l, T4e);
			      T4n = VSUB(T47, T4m);
			      T8C = VADD(T47, T4m);
			      T8z = VSUB(T8x, T8y);
			      T8A = VADD(T5T, T5U);
			      T8B = VFMA(LDK(KP707106781), T8A, T8z);
			      T8H = VFNMS(LDK(KP707106781), T8A, T8z);
			 }
			 T5D = VFMA(LDK(KP414213562), T3Z, T46);
			 T5E = VFNMS(LDK(KP414213562), T4e, T4l);
			 T5F = VADD(T5D, T5E);
			 T8I = VSUB(T5E, T5D);
			 {
			      V T5k, T5L, T5v, T5K, T5j, T5u;
			      T5j = VADD(T5b, T5i);
			      T5k = VFNMS(LDK(KP707106781), T5j, T54);
			      T5L = VFMA(LDK(KP707106781), T5j, T54);
			      T5u = VADD(T5s, T5t);
			      T5v = VFNMS(LDK(KP707106781), T5u, T5r);
			      T5K = VFMA(LDK(KP707106781), T5u, T5r);
			      T5w = VFNMS(LDK(KP668178637), T5v, T5k);
			      T5Q = VFMA(LDK(KP198912367), T5K, T5L);
			      T5A = VFMA(LDK(KP668178637), T5k, T5v);
			      T5M = VFNMS(LDK(KP198912367), T5L, T5K);
			 }
			 {
			      V T4L, T5I, T4W, T5H, T4K, T4V;
			      T4K = VADD(T4C, T4J);
			      T4L = VFNMS(LDK(KP707106781), T4K, T4v);
			      T5I = VFMA(LDK(KP707106781), T4K, T4v);
			      T4V = VADD(T4T, T4U);
			      T4W = VFNMS(LDK(KP707106781), T4V, T4S);
			      T5H = VFMA(LDK(KP707106781), T4V, T4S);
			      T4X = VFMA(LDK(KP668178637), T4W, T4L);
			      T5P = VFNMS(LDK(KP198912367), T5H, T5I);
			      T5z = VFNMS(LDK(KP668178637), T4L, T4W);
			      T5J = VFMA(LDK(KP198912367), T5I, T5H);
			 }
		    }
		    {
			 V T4o, T5x, T8J, T8K;
			 T4o = VFMA(LDK(KP923879532), T4n, T3S);
			 T5x = VSUB(T4X, T5w);
			 ST(&(ri[WS(rs, 21)]), VFNMS(LDK(KP831469612), T5x, T4o), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 5)]), VFMA(LDK(KP831469612), T5x, T4o), ms, &(ri[WS(rs, 1)]));
			 T8J = VFMA(LDK(KP923879532), T8I, T8H);
			 T8K = VSUB(T5A, T5z);
			 ST(&(ii[WS(rs, 5)]), VFMA(LDK(KP831469612), T8K, T8J), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 21)]), VFNMS(LDK(KP831469612), T8K, T8J), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T5y, T5B, T8L, T8M;
			 T5y = VFNMS(LDK(KP923879532), T4n, T3S);
			 T5B = VADD(T5z, T5A);
			 ST(&(ri[WS(rs, 13)]), VFNMS(LDK(KP831469612), T5B, T5y), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 29)]), VFMA(LDK(KP831469612), T5B, T5y), ms, &(ri[WS(rs, 1)]));
			 T8L = VFNMS(LDK(KP923879532), T8I, T8H);
			 T8M = VADD(T4X, T5w);
			 ST(&(ii[WS(rs, 13)]), VFNMS(LDK(KP831469612), T8M, T8L), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 29)]), VFMA(LDK(KP831469612), T8M, T8L), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T5G, T5N, T8D, T8E;
			 T5G = VFMA(LDK(KP923879532), T5F, T5C);
			 T5N = VADD(T5J, T5M);
			 ST(&(ri[WS(rs, 17)]), VFNMS(LDK(KP980785280), T5N, T5G), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 1)]), VFMA(LDK(KP980785280), T5N, T5G), ms, &(ri[WS(rs, 1)]));
			 T8D = VFMA(LDK(KP923879532), T8C, T8B);
			 T8E = VADD(T5P, T5Q);
			 ST(&(ii[WS(rs, 1)]), VFMA(LDK(KP980785280), T8E, T8D), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 17)]), VFNMS(LDK(KP980785280), T8E, T8D), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T5O, T5R, T8F, T8G;
			 T5O = VFNMS(LDK(KP923879532), T5F, T5C);
			 T5R = VSUB(T5P, T5Q);
			 ST(&(ri[WS(rs, 25)]), VFNMS(LDK(KP980785280), T5R, T5O), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 9)]), VFMA(LDK(KP980785280), T5R, T5O), ms, &(ri[WS(rs, 1)]));
			 T8F = VFNMS(LDK(KP923879532), T8C, T8B);
			 T8G = VSUB(T5M, T5J);
			 ST(&(ii[WS(rs, 9)]), VFMA(LDK(KP980785280), T8G, T8F), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 25)]), VFNMS(LDK(KP980785280), T8G, T8F), ms, &(ii[WS(rs, 1)]));
		    }
	       }
	       {
		    V T5W, T6o, T63, T8W, T8P, T8V, T6r, T8Q, T6i, T6C, T6m, T6y, T6b, T6B, T6l;
		    V T6v;
		    {
			 V T5S, T5V, T6p, T6q;
			 T5S = VSUB(T3w, T3B);
			 T5V = VSUB(T5T, T5U);
			 T5W = VFMA(LDK(KP707106781), T5V, T5S);
			 T6o = VFNMS(LDK(KP707106781), T5V, T5S);
			 {
			      V T5Z, T62, T8N, T8O;
			      T5Z = VFMA(LDK(KP414213562), T5Y, T5X);
			      T62 = VFNMS(LDK(KP414213562), T61, T60);
			      T63 = VSUB(T5Z, T62);
			      T8W = VADD(T5Z, T62);
			      T8N = VADD(T8y, T8x);
			      T8O = VSUB(T3Q, T3J);
			      T8P = VFMA(LDK(KP707106781), T8O, T8N);
			      T8V = VFNMS(LDK(KP707106781), T8O, T8N);
			 }
			 T6p = VFNMS(LDK(KP414213562), T5X, T5Y);
			 T6q = VFMA(LDK(KP414213562), T60, T61);
			 T6r = VADD(T6p, T6q);
			 T8Q = VSUB(T6q, T6p);
			 {
			      V T6e, T6x, T6h, T6w, T6d, T6g;
			      T6d = VSUB(T5i, T5b);
			      T6e = VFNMS(LDK(KP707106781), T6d, T6c);
			      T6x = VFMA(LDK(KP707106781), T6d, T6c);
			      T6g = VSUB(T5s, T5t);
			      T6h = VFNMS(LDK(KP707106781), T6g, T6f);
			      T6w = VFMA(LDK(KP707106781), T6g, T6f);
			      T6i = VFNMS(LDK(KP668178637), T6h, T6e);
			      T6C = VFMA(LDK(KP198912367), T6w, T6x);
			      T6m = VFMA(LDK(KP668178637), T6e, T6h);
			      T6y = VFNMS(LDK(KP198912367), T6x, T6w);
			 }
			 {
			      V T67, T6u, T6a, T6t, T66, T69;
			      T66 = VSUB(T4J, T4C);
			      T67 = VFNMS(LDK(KP707106781), T66, T65);
			      T6u = VFMA(LDK(KP707106781), T66, T65);
			      T69 = VSUB(T4T, T4U);
			      T6a = VFNMS(LDK(KP707106781), T69, T68);
			      T6t = VFMA(LDK(KP707106781), T69, T68);
			      T6b = VFMA(LDK(KP668178637), T6a, T67);
			      T6B = VFNMS(LDK(KP198912367), T6t, T6u);
			      T6l = VFNMS(LDK(KP668178637), T67, T6a);
			      T6v = VFMA(LDK(KP198912367), T6u, T6t);
			 }
		    }
		    {
			 V T64, T6j, T8R, T8S;
			 T64 = VFMA(LDK(KP923879532), T63, T5W);
			 T6j = VADD(T6b, T6i);
			 ST(&(ri[WS(rs, 19)]), VFNMS(LDK(KP831469612), T6j, T64), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 3)]), VFMA(LDK(KP831469612), T6j, T64), ms, &(ri[WS(rs, 1)]));
			 T8R = VFMA(LDK(KP923879532), T8Q, T8P);
			 T8S = VADD(T6l, T6m);
			 ST(&(ii[WS(rs, 3)]), VFMA(LDK(KP831469612), T8S, T8R), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 19)]), VFNMS(LDK(KP831469612), T8S, T8R), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T6k, T6n, T8T, T8U;
			 T6k = VFNMS(LDK(KP923879532), T63, T5W);
			 T6n = VSUB(T6l, T6m);
			 ST(&(ri[WS(rs, 27)]), VFNMS(LDK(KP831469612), T6n, T6k), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 11)]), VFMA(LDK(KP831469612), T6n, T6k), ms, &(ri[WS(rs, 1)]));
			 T8T = VFNMS(LDK(KP923879532), T8Q, T8P);
			 T8U = VSUB(T6i, T6b);
			 ST(&(ii[WS(rs, 11)]), VFMA(LDK(KP831469612), T8U, T8T), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 27)]), VFNMS(LDK(KP831469612), T8U, T8T), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T6s, T6z, T8X, T8Y;
			 T6s = VFNMS(LDK(KP923879532), T6r, T6o);
			 T6z = VSUB(T6v, T6y);
			 ST(&(ri[WS(rs, 23)]), VFNMS(LDK(KP980785280), T6z, T6s), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 7)]), VFMA(LDK(KP980785280), T6z, T6s), ms, &(ri[WS(rs, 1)]));
			 T8X = VFNMS(LDK(KP923879532), T8W, T8V);
			 T8Y = VSUB(T6C, T6B);
			 ST(&(ii[WS(rs, 7)]), VFMA(LDK(KP980785280), T8Y, T8X), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 23)]), VFNMS(LDK(KP980785280), T8Y, T8X), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T6A, T6D, T8Z, T90;
			 T6A = VFMA(LDK(KP923879532), T6r, T6o);
			 T6D = VADD(T6B, T6C);
			 ST(&(ri[WS(rs, 15)]), VFNMS(LDK(KP980785280), T6D, T6A), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 31)]), VFMA(LDK(KP980785280), T6D, T6A), ms, &(ri[WS(rs, 1)]));
			 T8Z = VFMA(LDK(KP923879532), T8W, T8V);
			 T90 = VADD(T6v, T6y);
			 ST(&(ii[WS(rs, 15)]), VFNMS(LDK(KP980785280), T90, T8Z), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 31)]), VFMA(LDK(KP980785280), T90, T8Z), ms, &(ii[WS(rs, 1)]));
		    }
	       }
	  }
     }
     VLEAVE();
}

static const tw_instr twinstr[] = {
     VTW(0, 1),
     VTW(0, 2),
     VTW(0, 3),
     VTW(0, 4),
     VTW(0, 5),
     VTW(0, 6),
     VTW(0, 7),
     VTW(0, 8),
     VTW(0, 9),
     VTW(0, 10),
     VTW(0, 11),
     VTW(0, 12),
     VTW(0, 13),
     VTW(0, 14),
     VTW(0, 15),
     VTW(0, 16),
     VTW(0, 17),
     VTW(0, 18),
     VTW(0, 19),
     VTW(0, 20),
     VTW(0, 21),
     VTW(0, 22),
     VTW(0, 23),
     VTW(0, 24),
     VTW(0, 25),
     VTW(0, 26),
     VTW(0, 27),
     VTW(0, 28),
     VTW(0, 29),
     VTW(0, 30),
     VTW(0, 31),
     { TW_NEXT, (2 * VL), 0 }
};

static const ct_desc desc = { 32, XSIMD_STRING("t1sv_32"), twinstr, &GENUS, { 236, 62, 198, 0 }, 0, 0, 0 };

void XSIMD(codelet_t1sv_32) (planner *p) {
     X(kdft_dit_register) (p, t1sv_32, &desc);
}
#else

/* Generated by: ../../../genfft/gen_twiddle.native -simd -compact -variables 4 -pipeline-latency 8 -n 32 -name t1sv_32 -include dft/simd/ts.h */

/*
 * This function contains 434 FP additions, 208 FP multiplications,
 * (or, 340 additions, 114 multiplications, 94 fused multiply/add),
 * 96 stack variables, 7 constants, and 128 memory accesses
 */
#include "dft/simd/ts.h"

static void t1sv_32(R *ri, R *ii, const R *W, stride rs, INT mb, INT me, INT ms)
{
     DVK(KP195090322, +0.195090322016128267848284868477022240927691618);
     DVK(KP980785280, +0.980785280403230449126182236134239036973933731);
     DVK(KP555570233, +0.555570233019602224742830813948532874374937191);
     DVK(KP831469612, +0.831469612302545237078788377617905756738560812);
     DVK(KP382683432, +0.382683432365089771728459984030398866761344562);
     DVK(KP923879532, +0.923879532511286756128183189396788286822416626);
     DVK(KP707106781, +0.707106781186547524400844362104849039284835938);
     {
	  INT m;
	  for (m = mb, W = W + (mb * 62); m < me; m = m + (2 * VL), ri = ri + ((2 * VL) * ms), ii = ii + ((2 * VL) * ms), W = W + ((2 * VL) * 62), MAKE_VOLATILE_STRIDE(64, rs)) {
	       V Tj, T5F, T7C, T7Q, T35, T4T, T78, T7m, T1Q, T61, T5Y, T6J, T3K, T59, T41;
	       V T56, T2B, T67, T6e, T6O, T4b, T5d, T4s, T5g, TG, T7l, T5I, T73, T3a, T4U;
	       V T3f, T4V, T14, T5N, T5M, T6E, T3m, T4Y, T3r, T4Z, T1r, T5P, T5S, T6F, T3x;
	       V T51, T3C, T52, T2d, T5Z, T64, T6K, T3V, T57, T44, T5a, T2Y, T6f, T6a, T6P;
	       V T4m, T5h, T4v, T5e;
	       {
		    V T1, T76, T6, T75, Tc, T32, Th, T33;
		    T1 = LD(&(ri[0]), ms, &(ri[0]));
		    T76 = LD(&(ii[0]), ms, &(ii[0]));
		    {
			 V T3, T5, T2, T4;
			 T3 = LD(&(ri[WS(rs, 16)]), ms, &(ri[0]));
			 T5 = LD(&(ii[WS(rs, 16)]), ms, &(ii[0]));
			 T2 = LDW(&(W[TWVL * 30]));
			 T4 = LDW(&(W[TWVL * 31]));
			 T6 = VFMA(T2, T3, VMUL(T4, T5));
			 T75 = VFNMS(T4, T3, VMUL(T2, T5));
		    }
		    {
			 V T9, Tb, T8, Ta;
			 T9 = LD(&(ri[WS(rs, 8)]), ms, &(ri[0]));
			 Tb = LD(&(ii[WS(rs, 8)]), ms, &(ii[0]));
			 T8 = LDW(&(W[TWVL * 14]));
			 Ta = LDW(&(W[TWVL * 15]));
			 Tc = VFMA(T8, T9, VMUL(Ta, Tb));
			 T32 = VFNMS(Ta, T9, VMUL(T8, Tb));
		    }
		    {
			 V Te, Tg, Td, Tf;
			 Te = LD(&(ri[WS(rs, 24)]), ms, &(ri[0]));
			 Tg = LD(&(ii[WS(rs, 24)]), ms, &(ii[0]));
			 Td = LDW(&(W[TWVL * 46]));
			 Tf = LDW(&(W[TWVL * 47]));
			 Th = VFMA(Td, Te, VMUL(Tf, Tg));
			 T33 = VFNMS(Tf, Te, VMUL(Td, Tg));
		    }
		    {
			 V T7, Ti, T7A, T7B;
			 T7 = VADD(T1, T6);
			 Ti = VADD(Tc, Th);
			 Tj = VADD(T7, Ti);
			 T5F = VSUB(T7, Ti);
			 T7A = VSUB(T76, T75);
			 T7B = VSUB(Tc, Th);
			 T7C = VSUB(T7A, T7B);
			 T7Q = VADD(T7B, T7A);
		    }
		    {
			 V T31, T34, T74, T77;
			 T31 = VSUB(T1, T6);
			 T34 = VSUB(T32, T33);
			 T35 = VSUB(T31, T34);
			 T4T = VADD(T31, T34);
			 T74 = VADD(T32, T33);
			 T77 = VADD(T75, T76);
			 T78 = VADD(T74, T77);
			 T7m = VSUB(T77, T74);
		    }
	       }
	       {
		    V T1y, T3G, T1O, T3Z, T1D, T3H, T1J, T3Y;
		    {
			 V T1v, T1x, T1u, T1w;
			 T1v = LD(&(ri[WS(rs, 1)]), ms, &(ri[WS(rs, 1)]));
			 T1x = LD(&(ii[WS(rs, 1)]), ms, &(ii[WS(rs, 1)]));
			 T1u = LDW(&(W[0]));
			 T1w = LDW(&(W[TWVL * 1]));
			 T1y = VFMA(T1u, T1v, VMUL(T1w, T1x));
			 T3G = VFNMS(T1w, T1v, VMUL(T1u, T1x));
		    }
		    {
			 V T1L, T1N, T1K, T1M;
			 T1L = LD(&(ri[WS(rs, 25)]), ms, &(ri[WS(rs, 1)]));
			 T1N = LD(&(ii[WS(rs, 25)]), ms, &(ii[WS(rs, 1)]));
			 T1K = LDW(&(W[TWVL * 48]));
			 T1M = LDW(&(W[TWVL * 49]));
			 T1O = VFMA(T1K, T1L, VMUL(T1M, T1N));
			 T3Z = VFNMS(T1M, T1L, VMUL(T1K, T1N));
		    }
		    {
			 V T1A, T1C, T1z, T1B;
			 T1A = LD(&(ri[WS(rs, 17)]), ms, &(ri[WS(rs, 1)]));
			 T1C = LD(&(ii[WS(rs, 17)]), ms, &(ii[WS(rs, 1)]));
			 T1z = LDW(&(W[TWVL * 32]));
			 T1B = LDW(&(W[TWVL * 33]));
			 T1D = VFMA(T1z, T1A, VMUL(T1B, T1C));
			 T3H = VFNMS(T1B, T1A, VMUL(T1z, T1C));
		    }
		    {
			 V T1G, T1I, T1F, T1H;
			 T1G = LD(&(ri[WS(rs, 9)]), ms, &(ri[WS(rs, 1)]));
			 T1I = LD(&(ii[WS(rs, 9)]), ms, &(ii[WS(rs, 1)]));
			 T1F = LDW(&(W[TWVL * 16]));
			 T1H = LDW(&(W[TWVL * 17]));
			 T1J = VFMA(T1F, T1G, VMUL(T1H, T1I));
			 T3Y = VFNMS(T1H, T1G, VMUL(T1F, T1I));
		    }
		    {
			 V T1E, T1P, T5W, T5X;
			 T1E = VADD(T1y, T1D);
			 T1P = VADD(T1J, T1O);
			 T1Q = VADD(T1E, T1P);
			 T61 = VSUB(T1E, T1P);
			 T5W = VADD(T3G, T3H);
			 T5X = VADD(T3Y, T3Z);
			 T5Y = VSUB(T5W, T5X);
			 T6J = VADD(T5W, T5X);
		    }
		    {
			 V T3I, T3J, T3X, T40;
			 T3I = VSUB(T3G, T3H);
			 T3J = VSUB(T1J, T1O);
			 T3K = VADD(T3I, T3J);
			 T59 = VSUB(T3I, T3J);
			 T3X = VSUB(T1y, T1D);
			 T40 = VSUB(T3Y, T3Z);
			 T41 = VSUB(T3X, T40);
			 T56 = VADD(T3X, T40);
		    }
	       }
	       {
		    V T2j, T4o, T2z, T49, T2o, T4p, T2u, T48;
		    {
			 V T2g, T2i, T2f, T2h;
			 T2g = LD(&(ri[WS(rs, 31)]), ms, &(ri[WS(rs, 1)]));
			 T2i = LD(&(ii[WS(rs, 31)]), ms, &(ii[WS(rs, 1)]));
			 T2f = LDW(&(W[TWVL * 60]));
			 T2h = LDW(&(W[TWVL * 61]));
			 T2j = VFMA(T2f, T2g, VMUL(T2h, T2i));
			 T4o = VFNMS(T2h, T2g, VMUL(T2f, T2i));
		    }
		    {
			 V T2w, T2y, T2v, T2x;
			 T2w = LD(&(ri[WS(rs, 23)]), ms, &(ri[WS(rs, 1)]));
			 T2y = LD(&(ii[WS(rs, 23)]), ms, &(ii[WS(rs, 1)]));
			 T2v = LDW(&(W[TWVL * 44]));
			 T2x = LDW(&(W[TWVL * 45]));
			 T2z = VFMA(T2v, T2w, VMUL(T2x, T2y));
			 T49 = VFNMS(T2x, T2w, VMUL(T2v, T2y));
		    }
		    {
			 V T2l, T2n, T2k, T2m;
			 T2l = LD(&(ri[WS(rs, 15)]), ms, &(ri[WS(rs, 1)]));
			 T2n = LD(&(ii[WS(rs, 15)]), ms, &(ii[WS(rs, 1)]));
			 T2k = LDW(&(W[TWVL * 28]));
			 T2m = LDW(&(W[TWVL * 29]));
			 T2o = VFMA(T2k, T2l, VMUL(T2m, T2n));
			 T4p = VFNMS(T2m, T2l, VMUL(T2k, T2n));
		    }
		    {
			 V T2r, T2t, T2q, T2s;
			 T2r = LD(&(ri[WS(rs, 7)]), ms, &(ri[WS(rs, 1)]));
			 T2t = LD(&(ii[WS(rs, 7)]), ms, &(ii[WS(rs, 1)]));
			 T2q = LDW(&(W[TWVL * 12]));
			 T2s = LDW(&(W[TWVL * 13]));
			 T2u = VFMA(T2q, T2r, VMUL(T2s, T2t));
			 T48 = VFNMS(T2s, T2r, VMUL(T2q, T2t));
		    }
		    {
			 V T2p, T2A, T6c, T6d;
			 T2p = VADD(T2j, T2o);
			 T2A = VADD(T2u, T2z);
			 T2B = VADD(T2p, T2A);
			 T67 = VSUB(T2p, T2A);
			 T6c = VADD(T4o, T4p);
			 T6d = VADD(T48, T49);
			 T6e = VSUB(T6c, T6d);
			 T6O = VADD(T6c, T6d);
		    }
		    {
			 V T47, T4a, T4q, T4r;
			 T47 = VSUB(T2j, T2o);
			 T4a = VSUB(T48, T49);
			 T4b = VSUB(T47, T4a);
			 T5d = VADD(T47, T4a);
			 T4q = VSUB(T4o, T4p);
			 T4r = VSUB(T2u, T2z);
			 T4s = VADD(T4q, T4r);
			 T5g = VSUB(T4q, T4r);
		    }
	       }
	       {
		    V To, T36, TE, T3d, Tt, T37, Tz, T3c;
		    {
			 V Tl, Tn, Tk, Tm;
			 Tl = LD(&(ri[WS(rs, 4)]), ms, &(ri[0]));
			 Tn = LD(&(ii[WS(rs, 4)]), ms, &(ii[0]));
			 Tk = LDW(&(W[TWVL * 6]));
			 Tm = LDW(&(W[TWVL * 7]));
			 To = VFMA(Tk, Tl, VMUL(Tm, Tn));
			 T36 = VFNMS(Tm, Tl, VMUL(Tk, Tn));
		    }
		    {
			 V TB, TD, TA, TC;
			 TB = LD(&(ri[WS(rs, 12)]), ms, &(ri[0]));
			 TD = LD(&(ii[WS(rs, 12)]), ms, &(ii[0]));
			 TA = LDW(&(W[TWVL * 22]));
			 TC = LDW(&(W[TWVL * 23]));
			 TE = VFMA(TA, TB, VMUL(TC, TD));
			 T3d = VFNMS(TC, TB, VMUL(TA, TD));
		    }
		    {
			 V Tq, Ts, Tp, Tr;
			 Tq = LD(&(ri[WS(rs, 20)]), ms, &(ri[0]));
			 Ts = LD(&(ii[WS(rs, 20)]), ms, &(ii[0]));
			 Tp = LDW(&(W[TWVL * 38]));
			 Tr = LDW(&(W[TWVL * 39]));
			 Tt = VFMA(Tp, Tq, VMUL(Tr, Ts));
			 T37 = VFNMS(Tr, Tq, VMUL(Tp, Ts));
		    }
		    {
			 V Tw, Ty, Tv, Tx;
			 Tw = LD(&(ri[WS(rs, 28)]), ms, &(ri[0]));
			 Ty = LD(&(ii[WS(rs, 28)]), ms, &(ii[0]));
			 Tv = LDW(&(W[TWVL * 54]));
			 Tx = LDW(&(W[TWVL * 55]));
			 Tz = VFMA(Tv, Tw, VMUL(Tx, Ty));
			 T3c = VFNMS(Tx, Tw, VMUL(Tv, Ty));
		    }
		    {
			 V Tu, TF, T5G, T5H;
			 Tu = VADD(To, Tt);
			 TF = VADD(Tz, TE);
			 TG = VADD(Tu, TF);
			 T7l = VSUB(TF, Tu);
			 T5G = VADD(T36, T37);
			 T5H = VADD(T3c, T3d);
			 T5I = VSUB(T5G, T5H);
			 T73 = VADD(T5G, T5H);
		    }
		    {
			 V T38, T39, T3b, T3e;
			 T38 = VSUB(T36, T37);
			 T39 = VSUB(To, Tt);
			 T3a = VSUB(T38, T39);
			 T4U = VADD(T39, T38);
			 T3b = VSUB(Tz, TE);
			 T3e = VSUB(T3c, T3d);
			 T3f = VADD(T3b, T3e);
			 T4V = VSUB(T3b, T3e);
		    }
	       }
	       {
		    V TM, T3i, T12, T3p, TR, T3j, TX, T3o;
		    {
			 V TJ, TL, TI, TK;
			 TJ = LD(&(ri[WS(rs, 2)]), ms, &(ri[0]));
			 TL = LD(&(ii[WS(rs, 2)]), ms, &(ii[0]));
			 TI = LDW(&(W[TWVL * 2]));
			 TK = LDW(&(W[TWVL * 3]));
			 TM = VFMA(TI, TJ, VMUL(TK, TL));
			 T3i = VFNMS(TK, TJ, VMUL(TI, TL));
		    }
		    {
			 V TZ, T11, TY, T10;
			 TZ = LD(&(ri[WS(rs, 26)]), ms, &(ri[0]));
			 T11 = LD(&(ii[WS(rs, 26)]), ms, &(ii[0]));
			 TY = LDW(&(W[TWVL * 50]));
			 T10 = LDW(&(W[TWVL * 51]));
			 T12 = VFMA(TY, TZ, VMUL(T10, T11));
			 T3p = VFNMS(T10, TZ, VMUL(TY, T11));
		    }
		    {
			 V TO, TQ, TN, TP;
			 TO = LD(&(ri[WS(rs, 18)]), ms, &(ri[0]));
			 TQ = LD(&(ii[WS(rs, 18)]), ms, &(ii[0]));
			 TN = LDW(&(W[TWVL * 34]));
			 TP = LDW(&(W[TWVL * 35]));
			 TR = VFMA(TN, TO, VMUL(TP, TQ));
			 T3j = VFNMS(TP, TO, VMUL(TN, TQ));
		    }
		    {
			 V TU, TW, TT, TV;
			 TU = LD(&(ri[WS(rs, 10)]), ms, &(ri[0]));
			 TW = LD(&(ii[WS(rs, 10)]), ms, &(ii[0]));
			 TT = LDW(&(W[TWVL * 18]));
			 TV = LDW(&(W[TWVL * 19]));
			 TX = VFMA(TT, TU, VMUL(TV, TW));
			 T3o = VFNMS(TV, TU, VMUL(TT, TW));
		    }
		    {
			 V TS, T13, T5K, T5L;
			 TS = VADD(TM, TR);
			 T13 = VADD(TX, T12);
			 T14 = VADD(TS, T13);
			 T5N = VSUB(TS, T13);
			 T5K = VADD(T3i, T3j);
			 T5L = VADD(T3o, T3p);
			 T5M = VSUB(T5K, T5L);
			 T6E = VADD(T5K, T5L);
		    }
		    {
			 V T3k, T3l, T3n, T3q;
			 T3k = VSUB(T3i, T3j);
			 T3l = VSUB(TX, T12);
			 T3m = VADD(T3k, T3l);
			 T4Y = VSUB(T3k, T3l);
			 T3n = VSUB(TM, TR);
			 T3q = VSUB(T3o, T3p);
			 T3r = VSUB(T3n, T3q);
			 T4Z = VADD(T3n, T3q);
		    }
	       }
	       {
		    V T19, T3t, T1p, T3A, T1e, T3u, T1k, T3z;
		    {
			 V T16, T18, T15, T17;
			 T16 = LD(&(ri[WS(rs, 30)]), ms, &(ri[0]));
			 T18 = LD(&(ii[WS(rs, 30)]), ms, &(ii[0]));
			 T15 = LDW(&(W[TWVL * 58]));
			 T17 = LDW(&(W[TWVL * 59]));
			 T19 = VFMA(T15, T16, VMUL(T17, T18));
			 T3t = VFNMS(T17, T16, VMUL(T15, T18));
		    }
		    {
			 V T1m, T1o, T1l, T1n;
			 T1m = LD(&(ri[WS(rs, 22)]), ms, &(ri[0]));
			 T1o = LD(&(ii[WS(rs, 22)]), ms, &(ii[0]));
			 T1l = LDW(&(W[TWVL * 42]));
			 T1n = LDW(&(W[TWVL * 43]));
			 T1p = VFMA(T1l, T1m, VMUL(T1n, T1o));
			 T3A = VFNMS(T1n, T1m, VMUL(T1l, T1o));
		    }
		    {
			 V T1b, T1d, T1a, T1c;
			 T1b = LD(&(ri[WS(rs, 14)]), ms, &(ri[0]));
			 T1d = LD(&(ii[WS(rs, 14)]), ms, &(ii[0]));
			 T1a = LDW(&(W[TWVL * 26]));
			 T1c = LDW(&(W[TWVL * 27]));
			 T1e = VFMA(T1a, T1b, VMUL(T1c, T1d));
			 T3u = VFNMS(T1c, T1b, VMUL(T1a, T1d));
		    }
		    {
			 V T1h, T1j, T1g, T1i;
			 T1h = LD(&(ri[WS(rs, 6)]), ms, &(ri[0]));
			 T1j = LD(&(ii[WS(rs, 6)]), ms, &(ii[0]));
			 T1g = LDW(&(W[TWVL * 10]));
			 T1i = LDW(&(W[TWVL * 11]));
			 T1k = VFMA(T1g, T1h, VMUL(T1i, T1j));
			 T3z = VFNMS(T1i, T1h, VMUL(T1g, T1j));
		    }
		    {
			 V T1f, T1q, T5Q, T5R;
			 T1f = VADD(T19, T1e);
			 T1q = VADD(T1k, T1p);
			 T1r = VADD(T1f, T1q);
			 T5P = VSUB(T1f, T1q);
			 T5Q = VADD(T3t, T3u);
			 T5R = VADD(T3z, T3A);
			 T5S = VSUB(T5Q, T5R);
			 T6F = VADD(T5Q, T5R);
		    }
		    {
			 V T3v, T3w, T3y, T3B;
			 T3v = VSUB(T3t, T3u);
			 T3w = VSUB(T1k, T1p);
			 T3x = VADD(T3v, T3w);
			 T51 = VSUB(T3v, T3w);
			 T3y = VSUB(T19, T1e);
			 T3B = VSUB(T3z, T3A);
			 T3C = VSUB(T3y, T3B);
			 T52 = VADD(T3y, T3B);
		    }
	       }
	       {
		    V T1V, T3R, T20, T3S, T3Q, T3T, T26, T3M, T2b, T3N, T3L, T3O;
		    {
			 V T1S, T1U, T1R, T1T;
			 T1S = LD(&(ri[WS(rs, 5)]), ms, &(ri[WS(rs, 1)]));
			 T1U = LD(&(ii[WS(rs, 5)]), ms, &(ii[WS(rs, 1)]));
			 T1R = LDW(&(W[TWVL * 8]));
			 T1T = LDW(&(W[TWVL * 9]));
			 T1V = VFMA(T1R, T1S, VMUL(T1T, T1U));
			 T3R = VFNMS(T1T, T1S, VMUL(T1R, T1U));
		    }
		    {
			 V T1X, T1Z, T1W, T1Y;
			 T1X = LD(&(ri[WS(rs, 21)]), ms, &(ri[WS(rs, 1)]));
			 T1Z = LD(&(ii[WS(rs, 21)]), ms, &(ii[WS(rs, 1)]));
			 T1W = LDW(&(W[TWVL * 40]));
			 T1Y = LDW(&(W[TWVL * 41]));
			 T20 = VFMA(T1W, T1X, VMUL(T1Y, T1Z));
			 T3S = VFNMS(T1Y, T1X, VMUL(T1W, T1Z));
		    }
		    T3Q = VSUB(T1V, T20);
		    T3T = VSUB(T3R, T3S);
		    {
			 V T23, T25, T22, T24;
			 T23 = LD(&(ri[WS(rs, 29)]), ms, &(ri[WS(rs, 1)]));
			 T25 = LD(&(ii[WS(rs, 29)]), ms, &(ii[WS(rs, 1)]));
			 T22 = LDW(&(W[TWVL * 56]));
			 T24 = LDW(&(W[TWVL * 57]));
			 T26 = VFMA(T22, T23, VMUL(T24, T25));
			 T3M = VFNMS(T24, T23, VMUL(T22, T25));
		    }
		    {
			 V T28, T2a, T27, T29;
			 T28 = LD(&(ri[WS(rs, 13)]), ms, &(ri[WS(rs, 1)]));
			 T2a = LD(&(ii[WS(rs, 13)]), ms, &(ii[WS(rs, 1)]));
			 T27 = LDW(&(W[TWVL * 24]));
			 T29 = LDW(&(W[TWVL * 25]));
			 T2b = VFMA(T27, T28, VMUL(T29, T2a));
			 T3N = VFNMS(T29, T28, VMUL(T27, T2a));
		    }
		    T3L = VSUB(T26, T2b);
		    T3O = VSUB(T3M, T3N);
		    {
			 V T21, T2c, T62, T63;
			 T21 = VADD(T1V, T20);
			 T2c = VADD(T26, T2b);
			 T2d = VADD(T21, T2c);
			 T5Z = VSUB(T2c, T21);
			 T62 = VADD(T3R, T3S);
			 T63 = VADD(T3M, T3N);
			 T64 = VSUB(T62, T63);
			 T6K = VADD(T62, T63);
		    }
		    {
			 V T3P, T3U, T42, T43;
			 T3P = VSUB(T3L, T3O);
			 T3U = VADD(T3Q, T3T);
			 T3V = VMUL(LDK(KP707106781), VSUB(T3P, T3U));
			 T57 = VMUL(LDK(KP707106781), VADD(T3U, T3P));
			 T42 = VSUB(T3T, T3Q);
			 T43 = VADD(T3L, T3O);
			 T44 = VMUL(LDK(KP707106781), VSUB(T42, T43));
			 T5a = VMUL(LDK(KP707106781), VADD(T42, T43));
		    }
	       }
	       {
		    V T2G, T4c, T2L, T4d, T4e, T4f, T2R, T4i, T2W, T4j, T4h, T4k;
		    {
			 V T2D, T2F, T2C, T2E;
			 T2D = LD(&(ri[WS(rs, 3)]), ms, &(ri[WS(rs, 1)]));
			 T2F = LD(&(ii[WS(rs, 3)]), ms, &(ii[WS(rs, 1)]));
			 T2C = LDW(&(W[TWVL * 4]));
			 T2E = LDW(&(W[TWVL * 5]));
			 T2G = VFMA(T2C, T2D, VMUL(T2E, T2F));
			 T4c = VFNMS(T2E, T2D, VMUL(T2C, T2F));
		    }
		    {
			 V T2I, T2K, T2H, T2J;
			 T2I = LD(&(ri[WS(rs, 19)]), ms, &(ri[WS(rs, 1)]));
			 T2K = LD(&(ii[WS(rs, 19)]), ms, &(ii[WS(rs, 1)]));
			 T2H = LDW(&(W[TWVL * 36]));
			 T2J = LDW(&(W[TWVL * 37]));
			 T2L = VFMA(T2H, T2I, VMUL(T2J, T2K));
			 T4d = VFNMS(T2J, T2I, VMUL(T2H, T2K));
		    }
		    T4e = VSUB(T4c, T4d);
		    T4f = VSUB(T2G, T2L);
		    {
			 V T2O, T2Q, T2N, T2P;
			 T2O = LD(&(ri[WS(rs, 27)]), ms, &(ri[WS(rs, 1)]));
			 T2Q = LD(&(ii[WS(rs, 27)]), ms, &(ii[WS(rs, 1)]));
			 T2N = LDW(&(W[TWVL * 52]));
			 T2P = LDW(&(W[TWVL * 53]));
			 T2R = VFMA(T2N, T2O, VMUL(T2P, T2Q));
			 T4i = VFNMS(T2P, T2O, VMUL(T2N, T2Q));
		    }
		    {
			 V T2T, T2V, T2S, T2U;
			 T2T = LD(&(ri[WS(rs, 11)]), ms, &(ri[WS(rs, 1)]));
			 T2V = LD(&(ii[WS(rs, 11)]), ms, &(ii[WS(rs, 1)]));
			 T2S = LDW(&(W[TWVL * 20]));
			 T2U = LDW(&(W[TWVL * 21]));
			 T2W = VFMA(T2S, T2T, VMUL(T2U, T2V));
			 T4j = VFNMS(T2U, T2T, VMUL(T2S, T2V));
		    }
		    T4h = VSUB(T2R, T2W);
		    T4k = VSUB(T4i, T4j);
		    {
			 V T2M, T2X, T68, T69;
			 T2M = VADD(T2G, T2L);
			 T2X = VADD(T2R, T2W);
			 T2Y = VADD(T2M, T2X);
			 T6f = VSUB(T2X, T2M);
			 T68 = VADD(T4c, T4d);
			 T69 = VADD(T4i, T4j);
			 T6a = VSUB(T68, T69);
			 T6P = VADD(T68, T69);
		    }
		    {
			 V T4g, T4l, T4t, T4u;
			 T4g = VSUB(T4e, T4f);
			 T4l = VADD(T4h, T4k);
			 T4m = VMUL(LDK(KP707106781), VSUB(T4g, T4l));
			 T5h = VMUL(LDK(KP707106781), VADD(T4g, T4l));
			 T4t = VSUB(T4h, T4k);
			 T4u = VADD(T4f, T4e);
			 T4v = VMUL(LDK(KP707106781), VSUB(T4t, T4u));
			 T5e = VMUL(LDK(KP707106781), VADD(T4u, T4t));
		    }
	       }
	       {
		    V T1t, T6X, T7a, T7c, T30, T7b, T70, T71;
		    {
			 V TH, T1s, T72, T79;
			 TH = VADD(Tj, TG);
			 T1s = VADD(T14, T1r);
			 T1t = VADD(TH, T1s);
			 T6X = VSUB(TH, T1s);
			 T72 = VADD(T6E, T6F);
			 T79 = VADD(T73, T78);
			 T7a = VADD(T72, T79);
			 T7c = VSUB(T79, T72);
		    }
		    {
			 V T2e, T2Z, T6Y, T6Z;
			 T2e = VADD(T1Q, T2d);
			 T2Z = VADD(T2B, T2Y);
			 T30 = VADD(T2e, T2Z);
			 T7b = VSUB(T2Z, T2e);
			 T6Y = VADD(T6J, T6K);
			 T6Z = VADD(T6O, T6P);
			 T70 = VSUB(T6Y, T6Z);
			 T71 = VADD(T6Y, T6Z);
		    }
		    ST(&(ri[WS(rs, 16)]), VSUB(T1t, T30), ms, &(ri[0]));
		    ST(&(ii[WS(rs, 16)]), VSUB(T7a, T71), ms, &(ii[0]));
		    ST(&(ri[0]), VADD(T1t, T30), ms, &(ri[0]));
		    ST(&(ii[0]), VADD(T71, T7a), ms, &(ii[0]));
		    ST(&(ri[WS(rs, 24)]), VSUB(T6X, T70), ms, &(ri[0]));
		    ST(&(ii[WS(rs, 24)]), VSUB(T7c, T7b), ms, &(ii[0]));
		    ST(&(ri[WS(rs, 8)]), VADD(T6X, T70), ms, &(ri[0]));
		    ST(&(ii[WS(rs, 8)]), VADD(T7b, T7c), ms, &(ii[0]));
	       }
	       {
		    V T6H, T6T, T7g, T7i, T6M, T6U, T6R, T6V;
		    {
			 V T6D, T6G, T7e, T7f;
			 T6D = VSUB(Tj, TG);
			 T6G = VSUB(T6E, T6F);
			 T6H = VADD(T6D, T6G);
			 T6T = VSUB(T6D, T6G);
			 T7e = VSUB(T1r, T14);
			 T7f = VSUB(T78, T73);
			 T7g = VADD(T7e, T7f);
			 T7i = VSUB(T7f, T7e);
		    }
		    {
			 V T6I, T6L, T6N, T6Q;
			 T6I = VSUB(T1Q, T2d);
			 T6L = VSUB(T6J, T6K);
			 T6M = VADD(T6I, T6L);
			 T6U = VSUB(T6L, T6I);
			 T6N = VSUB(T2B, T2Y);
			 T6Q = VSUB(T6O, T6P);
			 T6R = VSUB(T6N, T6Q);
			 T6V = VADD(T6N, T6Q);
		    }
		    {
			 V T6S, T7d, T6W, T7h;
			 T6S = VMUL(LDK(KP707106781), VADD(T6M, T6R));
			 ST(&(ri[WS(rs, 20)]), VSUB(T6H, T6S), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 4)]), VADD(T6H, T6S), ms, &(ri[0]));
			 T7d = VMUL(LDK(KP707106781), VADD(T6U, T6V));
			 ST(&(ii[WS(rs, 4)]), VADD(T7d, T7g), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 20)]), VSUB(T7g, T7d), ms, &(ii[0]));
			 T6W = VMUL(LDK(KP707106781), VSUB(T6U, T6V));
			 ST(&(ri[WS(rs, 28)]), VSUB(T6T, T6W), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 12)]), VADD(T6T, T6W), ms, &(ri[0]));
			 T7h = VMUL(LDK(KP707106781), VSUB(T6R, T6M));
			 ST(&(ii[WS(rs, 12)]), VADD(T7h, T7i), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 28)]), VSUB(T7i, T7h), ms, &(ii[0]));
		    }
	       }
	       {
		    V T5J, T7n, T7t, T6n, T5U, T7k, T6x, T6B, T6q, T7s, T66, T6k, T6u, T6A, T6h;
		    V T6l;
		    {
			 V T5O, T5T, T60, T65;
			 T5J = VSUB(T5F, T5I);
			 T7n = VADD(T7l, T7m);
			 T7t = VSUB(T7m, T7l);
			 T6n = VADD(T5F, T5I);
			 T5O = VSUB(T5M, T5N);
			 T5T = VADD(T5P, T5S);
			 T5U = VMUL(LDK(KP707106781), VSUB(T5O, T5T));
			 T7k = VMUL(LDK(KP707106781), VADD(T5O, T5T));
			 {
			      V T6v, T6w, T6o, T6p;
			      T6v = VADD(T67, T6a);
			      T6w = VADD(T6e, T6f);
			      T6x = VFNMS(LDK(KP382683432), T6w, VMUL(LDK(KP923879532), T6v));
			      T6B = VFMA(LDK(KP923879532), T6w, VMUL(LDK(KP382683432), T6v));
			      T6o = VADD(T5N, T5M);
			      T6p = VSUB(T5P, T5S);
			      T6q = VMUL(LDK(KP707106781), VADD(T6o, T6p));
			      T7s = VMUL(LDK(KP707106781), VSUB(T6p, T6o));
			 }
			 T60 = VSUB(T5Y, T5Z);
			 T65 = VSUB(T61, T64);
			 T66 = VFMA(LDK(KP923879532), T60, VMUL(LDK(KP382683432), T65));
			 T6k = VFNMS(LDK(KP923879532), T65, VMUL(LDK(KP382683432), T60));
			 {
			      V T6s, T6t, T6b, T6g;
			      T6s = VADD(T5Y, T5Z);
			      T6t = VADD(T61, T64);
			      T6u = VFMA(LDK(KP382683432), T6s, VMUL(LDK(KP923879532), T6t));
			      T6A = VFNMS(LDK(KP382683432), T6t, VMUL(LDK(KP923879532), T6s));
			      T6b = VSUB(T67, T6a);
			      T6g = VSUB(T6e, T6f);
			      T6h = VFNMS(LDK(KP923879532), T6g, VMUL(LDK(KP382683432), T6b));
			      T6l = VFMA(LDK(KP382683432), T6g, VMUL(LDK(KP923879532), T6b));
			 }
		    }
		    {
			 V T5V, T6i, T7r, T7u;
			 T5V = VADD(T5J, T5U);
			 T6i = VADD(T66, T6h);
			 ST(&(ri[WS(rs, 22)]), VSUB(T5V, T6i), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 6)]), VADD(T5V, T6i), ms, &(ri[0]));
			 T7r = VADD(T6k, T6l);
			 T7u = VADD(T7s, T7t);
			 ST(&(ii[WS(rs, 6)]), VADD(T7r, T7u), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 22)]), VSUB(T7u, T7r), ms, &(ii[0]));
		    }
		    {
			 V T6j, T6m, T7v, T7w;
			 T6j = VSUB(T5J, T5U);
			 T6m = VSUB(T6k, T6l);
			 ST(&(ri[WS(rs, 30)]), VSUB(T6j, T6m), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 14)]), VADD(T6j, T6m), ms, &(ri[0]));
			 T7v = VSUB(T6h, T66);
			 T7w = VSUB(T7t, T7s);
			 ST(&(ii[WS(rs, 14)]), VADD(T7v, T7w), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 30)]), VSUB(T7w, T7v), ms, &(ii[0]));
		    }
		    {
			 V T6r, T6y, T7j, T7o;
			 T6r = VADD(T6n, T6q);
			 T6y = VADD(T6u, T6x);
			 ST(&(ri[WS(rs, 18)]), VSUB(T6r, T6y), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 2)]), VADD(T6r, T6y), ms, &(ri[0]));
			 T7j = VADD(T6A, T6B);
			 T7o = VADD(T7k, T7n);
			 ST(&(ii[WS(rs, 2)]), VADD(T7j, T7o), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 18)]), VSUB(T7o, T7j), ms, &(ii[0]));
		    }
		    {
			 V T6z, T6C, T7p, T7q;
			 T6z = VSUB(T6n, T6q);
			 T6C = VSUB(T6A, T6B);
			 ST(&(ri[WS(rs, 26)]), VSUB(T6z, T6C), ms, &(ri[0]));
			 ST(&(ri[WS(rs, 10)]), VADD(T6z, T6C), ms, &(ri[0]));
			 T7p = VSUB(T6x, T6u);
			 T7q = VSUB(T7n, T7k);
			 ST(&(ii[WS(rs, 10)]), VADD(T7p, T7q), ms, &(ii[0]));
			 ST(&(ii[WS(rs, 26)]), VSUB(T7q, T7p), ms, &(ii[0]));
		    }
	       }
	       {
		    V T3h, T4D, T7R, T7X, T3E, T7O, T4N, T4R, T46, T4A, T4G, T7W, T4K, T4Q, T4x;
		    V T4B, T3g, T7P;
		    T3g = VMUL(LDK(KP707106781), VSUB(T3a, T3f));
		    T3h = VSUB(T35, T3g);
		    T4D = VADD(T35, T3g);
		    T7P = VMUL(LDK(KP707106781), VSUB(T4V, T4U));
		    T7R = VADD(T7P, T7Q);
		    T7X = VSUB(T7Q, T7P);
		    {
			 V T3s, T3D, T4L, T4M;
			 T3s = VFNMS(LDK(KP923879532), T3r, VMUL(LDK(KP382683432), T3m));
			 T3D = VFMA(LDK(KP382683432), T3x, VMUL(LDK(KP923879532), T3C));
			 T3E = VSUB(T3s, T3D);
			 T7O = VADD(T3s, T3D);
			 T4L = VADD(T4b, T4m);
			 T4M = VADD(T4s, T4v);
			 T4N = VFNMS(LDK(KP555570233), T4M, VMUL(LDK(KP831469612), T4L));
			 T4R = VFMA(LDK(KP831469612), T4M, VMUL(LDK(KP555570233), T4L));
		    }
		    {
			 V T3W, T45, T4E, T4F;
			 T3W = VSUB(T3K, T3V);
			 T45 = VSUB(T41, T44);
			 T46 = VFMA(LDK(KP980785280), T3W, VMUL(LDK(KP195090322), T45));
			 T4A = VFNMS(LDK(KP980785280), T45, VMUL(LDK(KP195090322), T3W));
			 T4E = VFMA(LDK(KP923879532), T3m, VMUL(LDK(KP382683432), T3r));
			 T4F = VFNMS(LDK(KP923879532), T3x, VMUL(LDK(KP382683432), T3C));
			 T4G = VADD(T4E, T4F);
			 T7W = VSUB(T4F, T4E);
		    }
		    {
			 V T4I, T4J, T4n, T4w;
			 T4I = VADD(T3K, T3V);
			 T4J = VADD(T41, T44);
			 T4K = VFMA(LDK(KP555570233), T4I, VMUL(LDK(KP831469612), T4J));
			 T4Q = VFNMS(LDK(KP555570233), T4J, VMUL(LDK(KP831469612), T4I));
			 T4n = VSUB(T4b, T4m);
			 T4w = VSUB(T4s, T4v);
			 T4x = VFNMS(LDK(KP980785280), T4w, VMUL(LDK(KP195090322), T4n));
			 T4B = VFMA(LDK(KP195090322), T4w, VMUL(LDK(KP980785280), T4n));
		    }
		    {
			 V T3F, T4y, T7V, T7Y;
			 T3F = VADD(T3h, T3E);
			 T4y = VADD(T46, T4x);
			 ST(&(ri[WS(rs, 23)]), VSUB(T3F, T4y), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 7)]), VADD(T3F, T4y), ms, &(ri[WS(rs, 1)]));
			 T7V = VADD(T4A, T4B);
			 T7Y = VADD(T7W, T7X);
			 ST(&(ii[WS(rs, 7)]), VADD(T7V, T7Y), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 23)]), VSUB(T7Y, T7V), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T4z, T4C, T7Z, T80;
			 T4z = VSUB(T3h, T3E);
			 T4C = VSUB(T4A, T4B);
			 ST(&(ri[WS(rs, 31)]), VSUB(T4z, T4C), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 15)]), VADD(T4z, T4C), ms, &(ri[WS(rs, 1)]));
			 T7Z = VSUB(T4x, T46);
			 T80 = VSUB(T7X, T7W);
			 ST(&(ii[WS(rs, 15)]), VADD(T7Z, T80), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 31)]), VSUB(T80, T7Z), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T4H, T4O, T7N, T7S;
			 T4H = VADD(T4D, T4G);
			 T4O = VADD(T4K, T4N);
			 ST(&(ri[WS(rs, 19)]), VSUB(T4H, T4O), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 3)]), VADD(T4H, T4O), ms, &(ri[WS(rs, 1)]));
			 T7N = VADD(T4Q, T4R);
			 T7S = VADD(T7O, T7R);
			 ST(&(ii[WS(rs, 3)]), VADD(T7N, T7S), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 19)]), VSUB(T7S, T7N), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T4P, T4S, T7T, T7U;
			 T4P = VSUB(T4D, T4G);
			 T4S = VSUB(T4Q, T4R);
			 ST(&(ri[WS(rs, 27)]), VSUB(T4P, T4S), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 11)]), VADD(T4P, T4S), ms, &(ri[WS(rs, 1)]));
			 T7T = VSUB(T4N, T4K);
			 T7U = VSUB(T7R, T7O);
			 ST(&(ii[WS(rs, 11)]), VADD(T7T, T7U), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 27)]), VSUB(T7U, T7T), ms, &(ii[WS(rs, 1)]));
		    }
	       }
	       {
		    V T4X, T5p, T7D, T7J, T54, T7y, T5z, T5D, T5c, T5m, T5s, T7I, T5w, T5C, T5j;
		    V T5n, T4W, T7z;
		    T4W = VMUL(LDK(KP707106781), VADD(T4U, T4V));
		    T4X = VSUB(T4T, T4W);
		    T5p = VADD(T4T, T4W);
		    T7z = VMUL(LDK(KP707106781), VADD(T3a, T3f));
		    T7D = VADD(T7z, T7C);
		    T7J = VSUB(T7C, T7z);
		    {
			 V T50, T53, T5x, T5y;
			 T50 = VFNMS(LDK(KP382683432), T4Z, VMUL(LDK(KP923879532), T4Y));
			 T53 = VFMA(LDK(KP923879532), T51, VMUL(LDK(KP382683432), T52));
			 T54 = VSUB(T50, T53);
			 T7y = VADD(T50, T53);
			 T5x = VADD(T5d, T5e);
			 T5y = VADD(T5g, T5h);
			 T5z = VFNMS(LDK(KP195090322), T5y, VMUL(LDK(KP980785280), T5x));
			 T5D = VFMA(LDK(KP195090322), T5x, VMUL(LDK(KP980785280), T5y));
		    }
		    {
			 V T58, T5b, T5q, T5r;
			 T58 = VSUB(T56, T57);
			 T5b = VSUB(T59, T5a);
			 T5c = VFMA(LDK(KP555570233), T58, VMUL(LDK(KP831469612), T5b));
			 T5m = VFNMS(LDK(KP831469612), T58, VMUL(LDK(KP555570233), T5b));
			 T5q = VFMA(LDK(KP382683432), T4Y, VMUL(LDK(KP923879532), T4Z));
			 T5r = VFNMS(LDK(KP382683432), T51, VMUL(LDK(KP923879532), T52));
			 T5s = VADD(T5q, T5r);
			 T7I = VSUB(T5r, T5q);
		    }
		    {
			 V T5u, T5v, T5f, T5i;
			 T5u = VADD(T56, T57);
			 T5v = VADD(T59, T5a);
			 T5w = VFMA(LDK(KP980785280), T5u, VMUL(LDK(KP195090322), T5v));
			 T5C = VFNMS(LDK(KP195090322), T5u, VMUL(LDK(KP980785280), T5v));
			 T5f = VSUB(T5d, T5e);
			 T5i = VSUB(T5g, T5h);
			 T5j = VFNMS(LDK(KP831469612), T5i, VMUL(LDK(KP555570233), T5f));
			 T5n = VFMA(LDK(KP831469612), T5f, VMUL(LDK(KP555570233), T5i));
		    }
		    {
			 V T55, T5k, T7H, T7K;
			 T55 = VADD(T4X, T54);
			 T5k = VADD(T5c, T5j);
			 ST(&(ri[WS(rs, 21)]), VSUB(T55, T5k), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 5)]), VADD(T55, T5k), ms, &(ri[WS(rs, 1)]));
			 T7H = VADD(T5m, T5n);
			 T7K = VADD(T7I, T7J);
			 ST(&(ii[WS(rs, 5)]), VADD(T7H, T7K), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 21)]), VSUB(T7K, T7H), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T5l, T5o, T7L, T7M;
			 T5l = VSUB(T4X, T54);
			 T5o = VSUB(T5m, T5n);
			 ST(&(ri[WS(rs, 29)]), VSUB(T5l, T5o), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 13)]), VADD(T5l, T5o), ms, &(ri[WS(rs, 1)]));
			 T7L = VSUB(T5j, T5c);
			 T7M = VSUB(T7J, T7I);
			 ST(&(ii[WS(rs, 13)]), VADD(T7L, T7M), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 29)]), VSUB(T7M, T7L), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T5t, T5A, T7x, T7E;
			 T5t = VADD(T5p, T5s);
			 T5A = VADD(T5w, T5z);
			 ST(&(ri[WS(rs, 17)]), VSUB(T5t, T5A), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 1)]), VADD(T5t, T5A), ms, &(ri[WS(rs, 1)]));
			 T7x = VADD(T5C, T5D);
			 T7E = VADD(T7y, T7D);
			 ST(&(ii[WS(rs, 1)]), VADD(T7x, T7E), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 17)]), VSUB(T7E, T7x), ms, &(ii[WS(rs, 1)]));
		    }
		    {
			 V T5B, T5E, T7F, T7G;
			 T5B = VSUB(T5p, T5s);
			 T5E = VSUB(T5C, T5D);
			 ST(&(ri[WS(rs, 25)]), VSUB(T5B, T5E), ms, &(ri[WS(rs, 1)]));
			 ST(&(ri[WS(rs, 9)]), VADD(T5B, T5E), ms, &(ri[WS(rs, 1)]));
			 T7F = VSUB(T5z, T5w);
			 T7G = VSUB(T7D, T7y);
			 ST(&(ii[WS(rs, 9)]), VADD(T7F, T7G), ms, &(ii[WS(rs, 1)]));
			 ST(&(ii[WS(rs, 25)]), VSUB(T7G, T7F), ms, &(ii[WS(rs, 1)]));
		    }
	       }
	  }
     }
     VLEAVE();
}

static const tw_instr twinstr[] = {
     VTW(0, 1),
     VTW(0, 2),
     VTW(0, 3),
     VTW(0, 4),
     VTW(0, 5),
     VTW(0, 6),
     VTW(0, 7),
     VTW(0, 8),
     VTW(0, 9),
     VTW(0, 10),
     VTW(0, 11),
     VTW(0, 12),
     VTW(0, 13),
     VTW(0, 14),
     VTW(0, 15),
     VTW(0, 16),
     VTW(0, 17),
     VTW(0, 18),
     VTW(0, 19),
     VTW(0, 20),
     VTW(0, 21),
     VTW(0, 22),
     VTW(0, 23),
     VTW(0, 24),
     VTW(0, 25),
     VTW(0, 26),
     VTW(0, 27),
     VTW(0, 28),
     VTW(0, 29),
     VTW(0, 30),
     VTW(0, 31),
     { TW_NEXT, (2 * VL), 0 }
};

static const ct_desc desc = { 32, XSIMD_STRING("t1sv_32"), twinstr, &GENUS, { 340, 114, 94, 0 }, 0, 0, 0 };

void XSIMD(codelet_t1sv_32) (planner *p) {
     X(kdft_dit_register) (p, t1sv_32, &desc);
}
#endif
