[tox]
envlist = py,lint,format

[testenv]
package = editable
deps = -r{toxinidir}/test-requirements.txt
commands = python -m pytest {posargs:tests}

[testenv:lint]
skip_install = true
deps = ruff==0.15.22
commands = ruff check {toxinidir}/pedalboard

[testenv:format]
skip_install = true
deps = ruff==0.15.22
commands = ruff format --check {toxinidir}/pedalboard --diff

[pytest]
testpaths = tests
